name: Release Build

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+u[0-9]+'
    paths-ignore:
      - '**/.gitignore'
      - '**/README.md'
      - .github/**
      - .tgitconfig
      - 'Release Notes.txt'
      - 'Build/**'

jobs:

  setup:
  
    if: github.repository == 'VixenLights/Vixen' || github.repository == 'jeffu231/Vixen'
  
    runs-on: windows-2019

    outputs:
      build_number: ${{ env.BUILD_NUMBER }}
      notes_build_type: ${{ env.VIX_NOTES_BUILD_TYPE }}
      notes_fix_version: ${{ env.VIX_NOTES_FIX_VERSION }}
      pre_release: ${{ env.VIX_PRE_RELEASE }}
      release_tag: ${{ env.VIX_RELEASE_TAG }}
      version: ${{ env.VIX_VERSION }}
      app_version: ${{ env.VIX_APP_VERSION }}
      environment: ${{ env.VIX_ENVIRONMENT }}

      
    steps:
    
      - uses: actions/checkout@v3

      steps:
      - name: create a custom version using run number offset by 1000 (run_number + 1000)
        run: |
          echo "BUILD_NUMBER=$((1000+GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Set variables
        shell: bash
        run: |
          if echo "${GITHUB_REF}" | grep -q "^refs/tags/" ;then
            VIX_RELEASE_TAG=$(echo "${GITHUB_REF}" | sed -e 's!^refs/tags/!!')
            set -- $(echo "${VIX_RELEASE_TAG}" | tr '.u' ' ')
  
            echo "VIX_NOTES_FIX_VERSION=DevBuild" >> $GITHUB_ENV
            echo "VIX_NOTES_BUILD_TYPE=${1}.${2}u${3:-0}" >> $GITHUB_ENV
            echo "VIX_ENVIRONMENT=Production" >> $GITHUB_ENV
            echo "VIX_RELEASE_TAG=${VIX_RELEASE_TAG}" >> $GITHUB_ENV
            echo "VIX_VERSION=${1}.${2}.${BUILD_NUMBER}.${3:-0}" >> $GITHUB_ENV
            echo "VIX_APP_VERSION=${1}.${2}.${3}" >> $GITHUB_ENV
          else
            echo "VIX_NOTES_FIX_VERSION=DevBuild" >> $GITHUB_ENV
            echo "VIX_NOTES_BUILD_TYPE=Development" >> $GITHUB_ENV
            echo "VIX_ENVIRONMENT=Development" >> $GITHUB_ENV
            echo "VIX_RELEASE_TAG=DevBuild-${BUILD_NUMBER}" >> $GITHUB_ENV
            echo "VIX_VERSION=0.0.${BUILD_NUMBER}.0" >> $GITHUB_ENV
            echo "VIX_APP_VERSION=0.0.${BUILD_NUMBER}" >> $GITHUB_ENV
          fi
          
      - name: show github env
        run: echo "${GITHUB_ENV}"
        
      - name: show github run number
        run: echo "${GITHUB_RUN_NUMBER}"

      - name: Update release notes
        run: ./Build/CreateReleaseNotes.ps1 -jiraUrl "http://bugs.vixenlights.com" -project "Vixen 3" -fixVersion "${env:VIX_NOTES_FIX_VERSION}" -buildType "${env:VIX_NOTES_BUILD_TYPE}"
      
      - name: Upload Release Notes artifact
        uses: actions/upload-artifact@v1
        with:
          name: _releaseNotes
          path: "Release Notes.txt"
          
      - name: Upload Build Release Notes Markdown artifact
        uses: actions/upload-artifact@v1
        with:
          name: _releaseNotesMd
          path: "Release Notes.md"


  build_x86:
  
    needs:
      - setup
    
    outputs:
      setup_32: ${{ env.SETUP_32 }}

    runs-on: windows-2019

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Download Release Notes artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: _releaseNotes
      
      - name: Move Release Notes into place
        run: Copy-Item "_releaseNotes\Release Notes.txt" -Destination "Release Notes.txt" -Force
        
      - uses: nuget/setup-nuget@v1
        
      - uses: microsoft/setup-msbuild@v1.1
      
      - name: NuGet Restore
        run: nuget restore Vixen.sln
        
      - name: Build x86
        run: msbuild Vixen.sln -m -t:Rebuild -p:Configuration=Deploy -p:Platform=x86 -p:Environment:${{ needs.setup.outputs.environment }} -p:App_Version=${{ needs.setup.outputs.app_version }} -p:Assembly_Version=${{ needs.setup.outputs.version }}
  
      - run: dir
        shell: cmd
        
      - name: Set installer name in environment
        shell: bash
        run: |
          echo "SETUP_32=$(echo Vixen*Setup-32bit.exe)" >> $GITHUB_ENV
        
      - name: Upload _setup32 artifact
        uses: actions/upload-artifact@v1
        with:
          name: _setup32
          path: Release\Setup\${{ needs.setup.outputs.environment }}\${{ env.SETUP_32 }}


  build_x64:
  
    needs:
      - setup
    
    outputs:
      setup_64: ${{ env.SETUP_64 }}

    runs-on: windows-2019

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Download Release Notes artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: _releaseNotes
      
      - name: Move Release Notes into place
        run: Copy-Item "_releaseNotes\Release Notes.txt" -Destination "Release Notes.txt" -Force
        
      - uses: nuget/setup-nuget@v1
        
      - uses: microsoft/setup-msbuild@v1.1
      
      - name: NuGet Restore
        run: nuget restore Vixen.sln
        
      - name: Build x64
        run: msbuild Vixen.sln -m -t:Rebuild -p:Configuration=Deploy -p:Platform=x64 -p:Environment:${{ needs.setup.outputs.environment }} -p:App_Version=${{ needs.setup.outputs.app_version }} -p:Assembly_Version=${{ needs.setup.outputs.version }}
  
      - run: dir
        shell: cmd
        
      - name: Set installer name in environment
        shell: bash
        run: |
          echo "SETUP_64=$(echo Vixen*Setup-64bit.exe)" >> $GITHUB_ENV

      - name: Upload _setup64 artifact
        uses: actions/upload-artifact@v1
        with:
          name: _setup64
          path: Release\Setup\${{ needs.setup.outputs.environment }}\${{ env.SETUP_64 }}


  create_release:
  
    if: github.repository == 'VixenLights/Vixen'
  
    needs:
      - setup
      - build_x86
      - build_x64

    runs-on: windows-2019

    steps:

      - name: Download _setup32 artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: _setup32
      
      - name: Download _setup64 artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: _setup64
          
      - name: Download Build Release Notes Markdown artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: _releaseNotesMd
          
      - name: Create release
        id: create_release
        uses: VixenLights/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.setup.outputs.release_tag }}
          release_name: ${{ needs.setup.outputs.release_tag }}
          body_path: _releaseNotesMd\Release Notes.md
          draft: false
          prerelease: ${{ needs.setup.outputs.pre_release }}
      
      - name: Upload x86 release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: _setup32/${{ needs.build_x86.outputs.setup_32 }}
          asset_name: ${{ needs.build_x86.outputs.setup_32 }}
          asset_content_type: application/vnd.microsoft.portable-executable
        
      - name: Upload x64 release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: _setup64/${{ needs.build_x64.outputs.setup_64 }}
          asset_name: ${{ needs.build_x64.outputs.setup_64 }}
          asset_content_type: application/vnd.microsoft.portable-executable

